#! /bin/sh -e

update-alternatives --quiet \
    --install /usr/bin/java java /usr/bin/gij-wrapper-@BV@ 33 \
    --slave /usr/share/man/man1/java.1.gz java.1.gz /usr/share/man/man1/gij-wrapper-@BV@.1.gz \
    --slave /usr/bin/rmiregistry rmiregistry /usr/bin/rmiregistry-@BV@ \
    --slave /usr/share/man/man1/rmiregistry.1.gz rmiregistry.1.gz /usr/share/man/man1/rmiregistry-@BV@.1.gz

#DEBHELPER#

exit 0
