\input texinfo

@setfilename porting.info
@settitle Porting libstdc++-v3
@setchapternewpage odd

@ifinfo
This file explains how to port libstdc++-v3 (the GNU C++ library) to 
a new target.

The documentation in this file was removed, because it is licencensed
under a non DFSG conforming licencse.
@end ifinfo

@c ---------------------------------------------------------------------
@c Titlepage
@c ---------------------------------------------------------------------

@titlepage
@title Porting libstdc++-v3
@author Mark Mitchell
@page
@vskip 0pt plus 1filll

The documentation in this file was removed, because it is licencensed
under a non DFSG conforming licencse.
@end titlepage

@c ---------------------------------------------------------------------
@c Top
@c ---------------------------------------------------------------------

@node Top
@top Porting libstdc++-v3

This document explains how to port libstdc++-v3 (the GNU C++ library) to 
a new target.

The documentation in this file was removed, because it is licencensed
under a non DFSG conforming licencse.

@c ---------------------------------------------------------------------
@c Epilogue
@c ---------------------------------------------------------------------

@contents
@bye
