#ifndef cursor_i_h
#define cursor_i_h

/*
 * DO NOT MODIFY
 *
 * This file was generated by ./a.out.
 *
 */

#define IP_OFF				8	/* 0x8 */
#define PR_OFF				24	/* 0x18 */
#define BSP_OFF				32	/* 0x20 */
#define PSP_OFF				48	/* 0x30 */
#define PFS_LOC_OFF			152	/* 0x98 */
#define RNAT_LOC_OFF			168	/* 0xa8 */
#define UNAT_LOC_OFF			328	/* 0x148 */
#define LC_LOC_OFF			360	/* 0x168 */
#define FPSR_LOC_OFF			376	/* 0x178 */
#define B1_LOC_OFF			392	/* 0x188 */
#define B2_LOC_OFF			408	/* 0x198 */
#define B3_LOC_OFF			424	/* 0x1a8 */
#define B4_LOC_OFF			440	/* 0x1b8 */
#define B5_LOC_OFF			456	/* 0x1c8 */
#define F2_LOC_OFF			472	/* 0x1d8 */
#define F3_LOC_OFF			488	/* 0x1e8 */
#define F4_LOC_OFF			504	/* 0x1f8 */
#define F5_LOC_OFF			520	/* 0x208 */
#define FR_LOC_OFF			536	/* 0x218 */
#define LOC_SIZE				16	/* 0x10 */
#define SIGCONTEXT_ADDR_OFF		824	/* 0x338 */

#endif /* cursor_i_h */
