#ifndef cursor_i_h
#define cursor_i_h

/*
 * DO NOT MODIFY
 *
 * This file was generated by ./a.out.
 *
 */

#define IP_OFF				8	/* 0x8 */
#define PR_OFF				24	/* 0x18 */
#define BSP_OFF				32	/* 0x20 */
#define PSP_OFF				48	/* 0x30 */
#define PFS_LOC_OFF			104	/* 0x68 */
#define RNAT_LOC_OFF			112	/* 0x70 */
#define UNAT_LOC_OFF			192	/* 0xc0 */
#define LC_LOC_OFF			208	/* 0xd0 */
#define FPSR_LOC_OFF			216	/* 0xd8 */
#define B1_LOC_OFF			224	/* 0xe0 */
#define B2_LOC_OFF			232	/* 0xe8 */
#define B3_LOC_OFF			240	/* 0xf0 */
#define B4_LOC_OFF			248	/* 0xf8 */
#define B5_LOC_OFF			256	/* 0x100 */
#define F2_LOC_OFF			264	/* 0x108 */
#define F3_LOC_OFF			272	/* 0x110 */
#define F4_LOC_OFF			280	/* 0x118 */
#define F5_LOC_OFF			288	/* 0x120 */
#define FR_LOC_OFF			296	/* 0x128 */
#define LOC_SIZE				8	/* 0x8 */
#define SIGCONTEXT_ADDR_OFF		456	/* 0x1c8 */

#endif /* cursor_i_h */
