#! /bin/sh -e

update-alternatives --quiet --remove java /usr/bin/gij-@BV@
update-alternatives --quiet --remove rmiregistry /usr/bin/grmiregistry-@BV@
update-alternatives --quiet --remove keytool /usr/bin/gkeytool-@BV@
update-alternatives --quiet --remove orbd /usr/bin/gorbd-@BV@
update-alternatives --quiet --remove rmid /usr/bin/grmid-@BV@
update-alternatives --quiet --remove serialver /usr/bin/gserialver-@BV@

#DEBHELPER#

exit 0
