
#if defined(__i486_linux_gnu__)
  { "64",  "x86_64-linux-gnu"},
#endif

#if defined(__powerpc64_linux_gnu__)
  { "32",  "powerpc-linux-gnu"},
#endif

#if defined(__x86_64_linux_gnu__)
  { "32",  "i486-linux-gnu"},
#endif

#if defined(__powerpc_linux_gnu__)
  { "64",  "powerpc64-linux-gnu"},
#endif

#if defined(__sparc_linux_gnu__)
  { "64",  "sparc64-linux-gnu"},
#endif

#if defined(__s390_linux_gnu__)
  { "64",  "s390x-linux-gnu"},
#endif

#if defined(__mips_linux_gnu__)
  { "n32",  "mips64-linux-gnuabin32"},
  { "64",  "mips64-linux-gnuabi64"},
#endif

#if defined(__mipsel_linux_gnu__)
  { "n32",  "mips64el-linux-gnuabin32"},
  { "64",  "mips64el-linux-gnuabi64"},
#endif

#if defined(__x86_64_kfreebsd_gnu__)
  { "32",  "i486-kfreebsd-gnu"},
#endif


